[package]
name = "eazy-keyframe"
description = "Keyframe animation support for the eazy animation library."
authors.workspace = true
license.workspace = true
repository = "https://github.com/invisageable/zo/tree/main/sources/tweener"
edition.workspace = true
version = "0.0.1"

[lib]
doctest = false

[dependencies]
# internal:sources.
eazy-core = { workspace = true }
eazy-tweener = { workspace = true }

# internal:crates.

# external:crates.

[dev-dependencies]
# internal:sources.

# internal:crates.

# external:crates.
criterion = { workspace = true }
insta = { workspace = true }
proptest = { workspace = true }
