[package]
name = "swisskit-io"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[features]
default = []
future = ["tokio"]

[dependencies]
# internal:sources.

# internal:crates.

# external:crates.
tokio = { workspace = true, optional = true }