[package]
name = "eazy-derive"
description = "Derive macros for the eazy animation library."
authors.workspace = true
license.workspace = true
repository = "https://github.com/invisageable/zo/tree/main/sources/tweener"
edition.workspace = true
version = "0.0.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
