[package]
name = "eazy-data"
edition.workspace = true
version = "0.0.0"

[lib]
doctest = false

[dependencies]
# internal:sources.

# internal:crates.
libm = { workspace = true }
wide = { workspace = true }

# external:crates.
