[package]
name = "zo-dce"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
# internal:sources.

# internal:crates.
zo-interner = { workspace = true }
zo-sir = { workspace = true }
zo-ty = { workspace = true }

# external:crates.
rustc-hash = { workspace = true }
