[package]
name = "eazy"
description = "The tweening & easing functions kit for high-performance animation."
repository = "https://github.com/invisageable/zo/tree/main/sources/tweener/eazy"
authors.workspace = true
license.workspace = true
edition.workspace = true
version = "0.0.1"

exclude = [
  "./benches/*",
]

keywords = [
  "easing",
  "interpolation",
  "animation",
]

[lib]
doctest = false

[features]
default = []
derive = ["eazy-derive"]
# wasm = ["eazy-wasm"]

[dependencies]
# internals:sources.
# eazy-bevy = { workspace = true, optional = true }
eazy-core = { workspace = true }
eazy-derive = { workspace = true, optional = true }
eazy-keyframe = { workspace = true }
eazy-tweener = { workspace = true }
# eazy-wasm = { workspace = true, optional = true }

# internals:crates.

# externals:crates.

[dev-dependencies]
# externals:crates.
criterion = { workspace = true }
fastrand = { workspace = true }

# bench:only.
bevy_tween = "0.11.0"
glissade = "0.2.6"
emath = "0.31.1"
easings = "0.1.0"
interpolation = "0.3.0"
keyframe = "1.1.1"
lilt = "0.8.1"
simple-easing2 = "1.0.2"

[[bench]]
name = "all"
harness = false
