[package]
name = "swisskit-core"
description = "The core of swisskit."
authors.workspace = true
license.workspace = true
edition.workspace = true
version = "0.0.0"

[lib]
doctest = false

[dependencies]
# internal:sources.

# internal:crates.

# external:crates.
flume = { workspace = true }
Inflector = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
smol_str = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
