[package]
name = "swisskit-renderer"
description = "A collection of renderers."
authors.workspace = true
license.workspace = true
edition.workspace = true
version = "0.0.0"

[lib]
doctest = false

[dependencies]
# internal:sources.

# internal:crates.

# external:crates.
ammonia = { workspace = true }
calamine = { workspace = true }
pulldown-cmark = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
log = { workspace = true }
pdfium-render = { workspace = true }
raw-window-handle = { workspace = true }
wry = { workspace = true }
