[package]
name = "zo-span"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
# internal:sources.

# internal:crates.

# external:crates.
anyhow ={ workspace = true }
serde = { workspace = true }
