[package]
name = "zo-codegen-arm"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
# internal:sources.

# internal:crates.
zo-buffer = { workspace = true }
zo-emitter-arm = { workspace = true }
zo-codegen-backend = { workspace = true }
zo-error = { workspace = true }
zo-interner = { workspace = true }
zo-reporter = { workspace = true }
zo-sir = { workspace = true }
zo-span = { workspace = true }
zo-ty = { workspace = true }
zo-ui-protocol = { workspace = true }
zo-value = { workspace = true }
zo-writer-macho = { workspace = true }

# external:crates.
rustc-hash = { workspace = true }

[dev-dependencies]
# internal:crates.
zo-analyzer = { workspace = true }
zo-executor = { workspace = true }
zo-parser = { workspace = true }
zo-token = { workspace = true }
zo-tokenizer = { workspace = true }

# external:crates.
criterion = { workspace = true }
insta = { workspace = true }
proptest = { workspace = true }

# [[bench]]
# name = "generate"
# harness = false
