[package]
name = "data-visualization-entrance-animation-with-out-elastic"
description = ""
version = "0.0.0"
repository = ""
edition = "2024"
publish = false

[lib]
doc-test = false

[dependencies]
eazy = { workspace = true }
