[package]
name = "eazy-core"
description = "Core of eazy animation library."
authors.workspace = true
license.workspace = true
repository = "https://github.com/invisageable/zo/tree/main/sources/tweener"
edition.workspace = true
version = "0.0.0"

[lib]
doctest = false

[dependencies]
# internal:sources.

# internal:crates.
libm = { workspace = true }
wide = { workspace = true }

# external:crates.
