[package]
name = "zo-pp"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
# internal:sources.

# internal:crates.
zo-buffer = { workspace = true }
zo-codegen-backend = { workspace = true }
zo-interner = { workspace = true }
zo-sir = { workspace = true }
zo-span = { workspace = true }
zo-token = { workspace = true }
zo-tree = { workspace = true }
zo-ty = { workspace = true }
zo-value = { workspace = true }

# external:crates.

[dev-dependencies]
