[package]
name = "egui-bouncing-ball-animation"
description = ""
version = "0.0.0"
repository = ""
edition = "2024"
publish = false

[dependencies]
eazy = { workspace = true, features = ["derive"] }
eframe = { workspace = true }
