[package]
name = "egui-bouncing-ball-animation"
description = ""
version = "0.0.0"
repository = ""
edition = "2024"
publish = false

[lib]
doc-test = false

[dependencies]
eframe = { workspace = true }
eazy = { workspace = true }
