[package]
name = "zo-runtime-native"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
# internal:sources.

# internal:crates.
zo-error = { workspace = true }
zo-reporter = { workspace = true }
zo-ui-protocol = { workspace = true }
zo-runtime-render = { workspace = true }

# external:crates.
eframe = { workspace = true }
libloading = { workspace = true }
serde = { workspace = true }
thin-vec = { workspace = true }
