[package]
name = "zo-tree"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
# internal:sources.

# internal:crates.
zo-interner = { workspace = true }
zo-span = { workspace = true }
zo-token = { workspace = true }

# external:crates.
serde = { workspace = true }
