[package]
name = "swisskit"
description = "The Swiss-Army-Knife kit for writing robust apps."
repository = "https://github.com/invisageable/zo/tree/main/sources/crafter/swisskit"
authors.workspace = true
license.workspace = true
edition.workspace = true
version = "0.0.0"

keywords = [
  "compilers",
  "renderers",
  "parsers",
  "utils",
]

[lib]
doctest = false

[features]
default = []

[dependencies]
# internal:sources.

# internal:crates.

# internal:crates.
swisskit-core = { workspace =  true }
swisskit-renderer = { workspace =  true }
