[package]
name = "swisskit"
repository = "https://github.com/invisageable/zo/tree/main/sources/crafter/swisskit"
version.workspace = true
edition.workspace = true

keywords = [
  "compilers",
  "renderers",
  "parsers",
  "utils",
]

[lib]
doctest = false

[features]
default = []

[dependencies]
# internal:sources.

# internal:crates.

# internal:crates.
swisskit-core = { workspace =  true }
swisskit-renderer = { workspace =  true }
