[package]
name = "swisskit"
repository = "https://github.com/invisageable/zo/tree/main/sources/crafter/swisskit"
version.workspace = true
edition.workspace = true

keywords = [
  "compilers",
  "renderers",
  "parsers",
  "utils",
]

[lib]
doctest = false

[features]
default = []
future = ["swisskit-io"]

[dependencies]
# internal:sources.

# internal:crates.

# internal:crates.
swisskit-case = { workspace = true }
swisskit-core = { workspace =  true }
swisskit-fmt = { workspace =  true }
swisskit-io = { workspace =  true, optional = true }
swisskit-renderer = { workspace =  true }
swisskit-span = { workspace =  true }
