[package]
name = "swisskit"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
# internal:sources.

# internal:crates.
swisskit-case = { workspace = true }
swisskit-renderer = { workspace =  true }
swisskit-span = { workspace =  true }

# external:crates.
flume = { workspace = true }
Inflector = { workspace = true }
regex = { workspace = true }
smol_str = { workspace = true }
