[package]
name = "zo-ty-state"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
# internal:sources.

# internal:crates.
zo-error = { workspace = true }
zo-tree = { workspace = true }
zo-interner = { workspace = true }
zo-span = { workspace = true }

# external:crates.
rustc-hash = { workspace = true }
serde = { workspace = true }
