[package]
name = "zo-token"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
# internal:sources.

# internal:crates.
zo-interner = { workspace = true }

# external:crates.
serde = { workspace = true }

